### ISSUE TITLE
Using proxy options with authentication leads to access violation exception.

### ISSUE THREAD

**Issue by tilomlr** [awslabs/aws-crt-java#161]
I'm glad to see that a proxy configuration is possible, but if I try to use the proxy options with basic authorization, **username and password** I get the following error:

#### Proxy Configuration

```
var proxy = new HttpProxyOptions();
proxy.setAuthorizationType(HttpProxyAuthorizationType.Basic);
proxy.setHost("<proxy-address>");
proxy.setPort(8080);
proxy.setAuthorizationUsername("<username>");
proxy.setAuthorizationPassword("<password>");
```

#### Error Message
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffc6f64137b, pid=16680, tid=9252
#
# JRE version: OpenJDK Runtime Environment (13.0.1+9) (build 13.0.1+9)
# Java VM: OpenJDK 64-Bit Server VM (13.0.1+9, mixed mode, sharing, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# C  [VCRUNTIME140D.dll+0x137b]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
```

**Comment by bretambrose** [comment]
Thanks for reporting this.  Before I look into it, I just want to verify a few things:

1. If you drop the user/pass requirement from the proxy setup and drop setting the username/pass in your application, does everything work properly?
1. If you drop setting the username/pass in your application (but keep it set on your proxy) do you just fail to connect or does something else bad happen?

**Comment by bretambrose** [comment]
We have a fix for this pending.  I will followup when we release it.
