### ISSUE TITLE
Provide an AWS CRT tailored to AWS Lambda

### ISSUE THREAD

**Issue by steffeng** [awslabs/aws-crt-java#235]
[AWS CRT HTTP Client](https://aws.amazon.com/blogs/developer/introducing-aws-common-runtime-http-client-in-the-aws-sdk-for-java-2-x/) is relevant for applications on AWS Lambda. However, the aws-crt library of 23 MB has an impact on bootstrap performance. Can you provide one that does not include all libs but linux/x86_64? Looks like you can bring it down to less than 6 MB this way.

**Comment by bretambrose** [comment]
This is in the works (https://github.com/awslabs/aws-crt-java/pull/222) but we don't have an ETA right now when it will be finished.

**Comment by TingDaoK** [comment]
https://github.com/awslabs/aws-crt-java#platform-specific-jars. We have introduced the platform specific jars from maven. Closing the issue, feel free to reopen if the maven packages not work for you.
