### ISSUE TITLE
CredentialsProvider should be an interface

### ISSUE THREAD

**Issue by aajtodd** [awslabs/aws-crt-java#252]
Currently [CredentialsProvider](https://github.com/awslabs/aws-crt-java/blob/main/src/main/java/software/amazon/awssdk/crt/auth/credentials/CredentialsProvider.java#L15) is an abstract base class that expects sub-classes to be native implementations. 

This prevents a library from providing a pure Java/Kotlin implementation of a credentials provider.

This should be refactored to an interface and the abstract base class can be made internal. The implementation will need to provide a bridge that wraps externally provided providers that proxies to C and back.

**Comment by bretambrose** [comment]
On the surface, this seems very reasonable.  We may not get to it for some time though.

**Comment by jmklix** [comment]
Closing. Use delegate credentials provider for similar functionality
