### ISSUE TITLE
closing HTTP stream after on_stream_complete fires causes segfault

### ISSUE THREAD

**Issue by aajtodd** [awslabs/aws-crt-java#262]
In the final HTTP request callback (from JNI side) the datastructure which contains the reference to the stream is released(free'd):

* https://github.com/awslabs/aws-crt-java/blob/main/src/native/http_request_response.c#L248
* https://github.com/awslabs/aws-crt-java/blob/main/src/native/http_request_response.c#L95

Which means that if you call `HttpStream.close()` from the JVM side AFTER the final callback then you will trigger a segfault in the JNI layer because the datastructure was already released:

* https://github.com/awslabs/aws-crt-java/blob/main/src/native/http_request_response.c#L367

```
stream = connection.makeRequest(...)

...

// sometime after the final callback

stream.close()  // segfault
```

Segfault usually happens in the call to [`aws_http_stream_release()`](https://github.com/awslabs/aws-crt-java/blob/main/src/native/http_request_response.c#L375) although every once in a while the null check on [L370](https://github.com/awslabs/aws-crt-java/blob/main/src/native/http_request_response.c#L370) actually triggered.

Resolution is either "don't do that" and better documentation or changes to prevent this possibility either through additional checks internally or at API level (i.e. if it is closed automagically in callback then don't provide a close method).

**Comment by jmklix** [comment]
Was this fixed with any of the above merged PR's?
