### ISSUE TITLE
expose credential expiration

### ISSUE THREAD

**Issue by aajtodd** [awslabs/aws-crt-java#294]
Credentials expiration time information should probably be exposed somehow

Preferably directly on the `Credentials` object (or at least a proxy to [aws_credentials_get_expiration_timepoint_seconds](https://github.com/awslabs/aws-c-auth/blob/main/include/aws/auth/credentials.h#L528))

**Comment by yasminetalby** [comment]
Hello @aajtodd ,

Thank you very much for your submission. My sincere apologies on the delay of answer on this. 
I wanted to provide an update, this feature request is currently in our backlog and in pending release state: https://github.com/awslabs/aws-crt-java-staging/pull/29/files#diff-5d98b473fe306d1f39c3336b95a98980e17c2473710e976a381bbae04e02067d
I will update this issue once it is available!

Thank you again for your feedback and contribution in the aws-crt-java feature.

Best regards,

Yasmine

**Comment by jmklix** [comment]
This is now available
