### ISSUE TITLE
Error in http_connection_manager.c (aws_jni_check_and_clear_exception)

### ISSUE THREAD

**Issue by b-liberman** [awslabs/aws-crt-java#312]
Hello, 

we receive this error:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/22765155/116355008-85e4ed00-a7f9-11eb-8cff-17191696f374.png)

If this error occurs, the entire java process gets hung up.

This error might be somehow related to concurrency as we observed that if we reduce the fork count in maven to 1 then the error would occur less often, but it still occurs.

Unfortunately, I cannot provide any more context on this error as it is not possible to debug in Java.

Regards

Boris

**Comment by bretambrose** [comment]
I feel like a lot more context could be given here:

What does your program do?
What is it doing when this happens?
What are the platform details of the execution environment?

Looking at the screenshot I see calls to signChunk (which may be misleading somehow) and I don't know of any current CRT use case that would be using that particular functionality right now.  Can you give more details as to how you're using the CRT?  Is it from the AWS Java SDK?

**Comment by b-liberman** [comment]
Our program reads and writes from Kinesis using KCL. KCL internally communicates with DynamoDB and Cloudwatch. Additionally, we also write data to Cloudwatch and Cloudwatch logs.
We use CRT because we are located behind a proxy, which requires authentication - which is not supported by the standard Netty client. Thus, we configured KCL and other components to use CRT.

As you can see from the screenshot, we are not getting any further information when this error occurs.
Our versions are:
java 8
amazon-kinesis-client: 2.3.4
aws-crt-client: 2.16.64-PREVIEW
amazon-sdk.version: 2.16.64

**Comment by bretambrose** [comment]
I see the problem and am a little shocked how obvious it is and that it hasn't hit before.  I'll try to look closer as soon as I get finished with some high-severity requests.

**Comment by b-liberman** [comment]
is there maybe a timeline for a fix that you could provide me?
Thanks!

**Comment by bretambrose** [comment]
Apologies, still trying to work through some internal release priorities.  Might be able to get to it late this week.

**Comment by bretambrose** [comment]
v0.13.6 should contain the fix for this issue and be available shortly.
