### ISSUE TITLE
Support for devloping on MAC M1

### ISSUE THREAD

**Issue by mikkeldamsgaard** [awslabs/aws-crt-java#371]
It seems that the latests jar that is pushed to maven does not include binaries for MAC M1's.

Unable to open library in jar for AWS CRT: /osx/armv8/libaws-crt-jni.dylib

**Comment by jonasbark** [comment]
As a workaround, you can install it to your local maven repository and reference it in your project :)

**Comment by michaelbrewer** [comment]
This breaks using the aws kotlin sdk on m1.

**Comment by cprice404** [comment]
Is there any ETA for this?  Or documentation of workaround steps?  Apple is no longer shipping macs that are not m1.

**Comment by kvcache** [comment]
This compiles on M1 macs. You can `mvn install` it; it generates the `osx/armv8/libaws-crt-jni.dylib`, tests pass... Just needs this native target included in the artifacts like regular osx and android.

**Comment by RobertoUa** [comment]
any news?

**Comment by dgm90** [comment]
Please, provide some good news 🙏🏼

**Comment by vcanuel** [comment]
Hi this is fixed by https://github.com/awslabs/aws-crt-java/pull/479
