### ISSUE TITLE
public artifact is bundling unneeded files

### ISSUE THREAD

**Issue by kggilmer** [awslabs/aws-crt-java#390]
The public jar hosted on maven central contains some object files and other files that are not needed:

```bash
$ wget https://repo1.maven.org/maven2/software/amazon/awssdk/crt/aws-crt/0.15.2/aws-crt-0.15.2.jar
$ zipinfo aws-crt-0.15.2.jar | grep -v .class | grep -v \^d
Archive:  aws-crt-0.15.2.jar
Zip file size: 13872692 bytes, number of entries: 1506
-rw-r--r--  2.0 unx      384 bl defN 21-Sep-24 23:15 META-INF/MANIFEST.MF
-rw-r--r--  2.0 unx  3095628 bl defN 21-Sep-24 23:14 linux/armv7/libaws-crt-jni.so
-rw-r--r--  2.0 unx  3056688 bl defN 21-Sep-24 23:14 linux/armv6/libaws-crt-jni.so
-rw-r--r--  2.0 unx  1588224 bl defN 21-Sep-24 23:14 windows/x86_64/aws-crt-jni.dll
-rw-r--r--  2.0 unx  1222144 bl defN 21-Sep-24 23:14 windows/x86_32/aws-crt-jni.dll
-rw-r--r--  2.0 unx  1380520 bl defN 21-Sep-24 23:14 osx/x86_64/libaws-crt-jni.dylib
-rw-r--r--  2.0 unx    17461 bl defN 21-Sep-24 23:15 META-INF/maven/software.amazon.awssdk.crt/aws-crt/pom.xml
-rw-r--r--  2.0 unx      100 bl defN 21-Sep-24 23:15 META-INF/maven/software.amazon.awssdk.crt/aws-crt/pom.properties
-rw-r--r--  2.0 unx  3759864 bl defN 21-Sep-24 23:14 linux/x86_64/libaws-crt-jni.so
-rw-r--r--  2.0 unx  3676424 bl defN 21-Sep-24 23:14 linux/armv8/libaws-crt-jni.so
-rw-r--r--  2.0 unx  3408100 bl defN 21-Sep-24 23:14 linux/x86_32/libaws-crt-jni.so
-rw-r--r--  2.0 unx   292160 bl defN 21-Sep-24 23:14 libaws-c-event-stream.a
-rw-r--r--  2.0 unx 10337584 bl defN 21-Sep-24 23:14 libs2n.a
1506 files, 34201166 bytes uncompressed, 13563974 bytes compressed:  60.3%
```

**Comment by xsnrg** [comment]
This is still in Open status, but does anyone know if this is still the case for the most recent versions? Running into this with 0.16.1

**Comment by bretambrose** [comment]
Following the listed instructions against the latest version, I no longer see the .a files in the jar.

**Comment by xsnrg** [comment]
unfortunately, the .dll files being mixed in cause applications like the OWASP dependency checker (https://owasp.org/www-project-dependency-check/) to see that there are DLL files and request one to install .NET into a 100% Java/Linux environment in order to scan the included DLLs. I took this ticket to mean that none of the OS specific libraries should be included in the jar file. Perhaps that was not @kggilmer 's intention though.

**Comment by bretambrose** [comment]
The published jar currently contains the native shared objects for all supported platform/arch combinations by design. How you could possibly split and conditionally use only what you wanted is an open question for us currently.

**Comment by xsnrg** [comment]
Thanks for the follow-up @bretambrose
