### ISSUE TITLE
Custom ports in the S3Client

### ISSUE THREAD

**Issue by aceeric** [awslabs/aws-crt-java#431]
This relates to the AWS Java SDK V2 pull request: https://github.com/aws/aws-sdk-java-v2/pull/2976

The PR relates to using the SDK `TransferManager` to parallelize downloads of large objects. In our testing, this parallelization results in large objects downloading up to 5X faster than non-parallel downloads. The pull request refers to using the CRT `S3Client` class. In looking at CRT code, the `S3Client` class makes its way down into the JNI layer and ultimately winds up resolving a connection to either 80 or 443 (hard-coded.)

We would like to use the SDK `TransferManager` functionality in a Kubernetes environment with an S3-compliant object store (e.g. Minio) and would like the flexibility to use different ports both inside the cluster and also outside the cluster to support - for example - desktop testing via port-forwarding.

To support this, the CRT `S3Client` and the JNI `s3ClientNew` method (and related lower-level C functions) would need to be modified to allow a custom port, much like the custom endpoint that is currently accepted. This would replace the 80/443 hardcodes.

We've already done some experimentation with this and the change does  not seem too pervasive if localized to the S3Client and below. Before investing the effort in a PR - I wanted to get your views on whether you would accept such a PR - or - if you're already working on changes to support custom ports in the CRT in the future. Thank you.

**Comment by JonathanHenson** [comment]
It SHOULD simply be pulled from the endpoint you pass (e.g. http://dnsname:port). If the port is not honored, it's a bug and we need to fix it.

**Comment by ron1** [comment]
@JonathanHenson Note that in the following test (here)[https://github.com/awslabs/aws-crt-java/blob/7adb0e6ed09fe8fbd28f179e4d1c7bb412da5ddf/src/test/java/software/amazon/awssdk/crt/test/S3ClientTest.java#L37], ENDPOINT is the dnsname of a host. Based on your comment, should it instead be https://dnsname:443 where the :443 suffix is optional? I believe changing the test to include the https protocol in the endpoint results in a dns host resolver error. Am I correct such an error should be considered a bug?

**Comment by aceeric** [comment]
@JonathanHenson As I read the code:

1. In `aws-c-s3`, file `source/s3_client.c` has function `aws_s3_client_make_meta_request` which is called by the AWS SDK V2 Java code as a result of a `getObject` SDK call
2. That function gets the host header here: https://github.com/awslabs/aws-c-s3/blob/2c2ff56c21e075cdd87f68b36606991efa731a47/source/s3_client.c#L615
3. Further down, this header value gets copied into an `aws_s3_endpoint_options` struct
4. That struct gets converted into an `aws_s3_endpoint` struct via a call to `aws_s3_endpoint_new`
5. `aws_s3_endpoint_new`  does this by initializing `host_resolver_config.impl` with function `aws_default_dns_resolve` and passes the host name and `host_resolver_config` as args to the `aws_host_resolver_resolve_host` function
6. That function - through the vtable - calls a `resolve_host` function passing the struct that has pointer to function `aws_default_dns_resolve` in its `impl` field - which ultimately gets called - this fxn is in `posix/host_resolver.c` in `aws-c-io`
7. That function on Linux calls the `getaddrinfo` OS function passing the host name and if you send anything in there other than a host or IP (I've tested with :80 appended) if  returns error AWS_IO_DNS_INVALID_NAME which you can see all the way up into that AWS SDK call stack

So - it looks intentional to me that the current code treats the host header as strictly a host name or IP address. I my prototyping I was more conservative. (This ticket also relates to https://github.com/awslabs/aws-crt-java/issues/432.) In both cases my thinking was to add additional args to the JNI signature to accomplish http vs https (e.g. `tlsEnabled`) as well as a custom port arg (e.g. `port`.)

But if it makes more sense to accept a host header in the form `host` or `host:port` then for this ticket I could take this approach:

1. Get the host header from the caller as is currently done
2. Split out the port and pass just the host name on down for DNS resolution
3. Modify `s_s3_endpoint_create_http_connection_manager` in `s3_endpoint.c` to allow overriding the port hard-codes if a custom port is provided

Which do you think is best? Thanks.

**Comment by JonathanHenson** [comment]
It seems the issue would be better if we took a separate endpoint argument, and we parsed it as a URI. Then the uri determine port and scheme.

**Comment by aceeric** [comment]
This is a more detailed description of the approach I propose. Note - this is a tad different from your recommendation but is informed by how the CRT `http/HttpClientConnectionManager` class approaches the same problem:
```
- modify the software.amazon.awssdk.crt.s3.S3MetaRequestOptions class:
  - include a new field java.net.uri.URI uri
- modify the software.amazon.awssdk.crt.s3.S3Client - makeMetaRequest Java method:
  - if the S3MetaRequestOptions arg contains a non-null URI:
    - calculate and replace the "Host" header using the host only (no port) from the
      URI before the call to s3ClientMakeMetaRequest
    - determine protocol and port from URI
    - add arguments for both protocol (boolean useTls) and port (int port) to the
      s3ClientMakeMetaRequest JNI method
      - can be null/zero
      - parse these in the Java like HttpClientConnectionManager to minimize string parsing,
        mem mgmt etc. in the C code
  - else if the S3MetaRequestOptions arg contains a null URI:
    - current functionality
- modify src/native/s3_client.c Java_software_amazon_awssdk_crt_s3_S3Client_s3ClientMakeMetaRequest
  JNI function:
  - accept new useTls and port args
  - modify aws_s3_meta_request_options to carry these fields
- modify source/s3_client.c:
  - modify aws_s3_endpoint_options struct to carry the two new fields under discussion
- modify source/s3_endpoint.c
  - modify call to s_s3_endpoint_create_http_connection_manager to accept two new fields
  - modify function s_s3_endpoint_create_http_connection_manager to pay attention to protocol and port
```
Please let me know your thoughts. Thank you.

**Comment by aceeric** [comment]
@JonathanHenson please review the PR at: https://github.com/awslabs/aws-crt-java/pull/435. Thank you.

**Comment by aceeric** [comment]
Hello folks - is anyone available to provide some feedback on this PR? Thank you.

**Comment by TingDaoK** [comment]
PR merged and new release published with the fix
