### ISSUE TITLE
Improve Performance of Debug Native Object tracking

### ISSUE THREAD

**Issue by alexw91** [awslabs/aws-crt-java#433]
In [a previous Pull Request](https://github.com/awslabs/aws-crt-java/pull/323/files#diff-f1aab4617eaab3b72c27aba06813c82260b9c539ca342e58824feaed4e7c4974L74-R79) a change was made to replace the backing native resource object map in debug mode from a `ConcurrentHashMap` to a `HashMap` that used the `synchronized` keyword on the class name around all accesses. 

While this implementation is also correct, it has slower performance than continuing to use `ConcurrentHashMap` when in debug mode. Synchronization will lock the entire HashMap any time any thread is adding or removing any time from the Map, and will cause contention issues if multiple threads are making reads/writes simultaneously. Whereas ConcurrentHashMap only locks a small inner subset of the backing Map during reads/writes, and makes it much less likely that two threads will create contention issues if both are making modifications simultaneously.

For more info on this, see:
 - https://web.archive.org/web/20210122220134/https://www.ibm.com/developerworks/java/library/j-jtp08223/index.html
 - https://stackoverflow.com/questions/1291836/concurrenthashmap-vs-synchronized-hashmap
 - https://www.geeksforgeeks.org/difference-between-concurrenthashmap-and-synchronizedhashmap/

**Comment by bretambrose** [comment]
Please see comment on comment.
