### ISSUE TITLE
MqttClientConnectionEvents.onConnectionResumed is not called on first successful connect

### ISSUE THREAD

**Issue by j123b567** [awslabs/aws-crt-java#446]
In the documentation https://awslabs.github.io/aws-crt-java/software/amazon/awssdk/crt/mqtt/MqttClientConnectionEvents.html#onConnectionResumed(boolean) there is stated, that `onConnectionResumed` is "called on first successful connect, and whenever a reconnect succeeds".

Based on observations on `BasicPubSub` client from `aws-iot-device-sdk-java-v2` `onConnectionResumed` is never called **on first successful connect**.

So there is a bug in the documentation or in the code.

Tested with MQTT over WebSocket with
 - aws-rct-java v0.15.18
 - aws-iot-device-sdk-java-v2 v1.6.1

```
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (Temurin)(build 25.312-b07, mixed mode)
```

```
openjdk version "11.0.14" 2022-01-18
OpenJDK Runtime Environment Temurin-11.0.14+9 (build 11.0.14+9)
OpenJDK 64-Bit Server VM Temurin-11.0.14+9 (build 11.0.14+9, mixed mode)
```

`onConnectionResumed` is the only place where one should place subscriptions to topcis so they can survive reconnects. When this callback is not called on the first connect, there must be special handling for the first connect and for every other connect in user code.

**Comment by bretambrose** [comment]
This was a mistake in the documentation.  https://github.com/awslabs/aws-crt-java/pull/588 corrects it and the io doc page should be updated on the next release.
