### ISSUE TITLE
using crt with Linux Alpine jvm crash 

### ISSUE THREAD

**Issue by LIANGQI0811** [awslabs/aws-crt-java#500]
jvm crashes when i use s3's mrap to generate presigned url.

my doker file is:
`FROM openjdk8`
`RUN  ln -s /lib /lib64 && apk add --no-cache libc6-compat linux-pam krb5 krb5-libs`

uname -a results:
`Linux test-service-deployment-xxxx-xxxx 5.4.181-99.354.amzn2.x86_64 #1 SMP Wed Mar 2 18:50:46 UTC 2022 x86_64 Linux`

and I using pom:
```
<aws.java.sdk.version>2.17.206</aws.java.sdk.version>

<dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>auth-crt</artifactId>
            <version>${aws.java.sdk.version}</version>
</dependency>

```
and the jvm crashed with message :
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000000065eb6, pid=9, tid=0x00007f08b03fdb10
#
# JRE version: OpenJDK Runtime Environment (8.0_212-b04) (build 1.8.0_212-b04)
# Java VM: OpenJDK 64-Bit Server VM (25.212-b04 mixed mode linux-amd64 compressed oops)
# Derivative: IcedTea 3.12.0
# Distribution: Custom build (Sat May  4 17:33:35 UTC 2019)
# Problematic frame:
# C  0x0000000000065eb6
#
# Core dump written. Default location: //core or core.9
#
# An error report file with more information is saved as:
# //hs_err_pid9.log
#
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
#   https://icedtea.classpath.org/bugzilla
#
```

**Comment by LIANGQI0811** [comment]
my java code like this:
`public class S3MultiRegionPreSigner implements Signer {

    private final S3Presigner s3Presigner;

    private final String arn;

    @Getter
    private final String tmpBucket;

    public S3MultiRegionPreSigner(PreSignerProperties preSignerProperties) {
        StaticCredentialsProvider credentialsProvider =
                StaticCredentialsProvider.create(AwsBasicCredentials.create(preSignerProperties.getAk(), preSignerProperties.getSk()));
        this.s3Presigner = S3Presigner.builder()
                .region(Region.of(preSignerProperties.getRegion()))
                .credentialsProvider(credentialsProvider)
                .build();
        this.arn = preSignerProperties.getArn();
        this.tmpBucket = preSignerProperties.getTmpBucket();
    }

    @Override
    public String getPresignUrl(String bucketName, String objectName, Duration duration) {
        PutObjectRequest objectRequest = PutObjectRequest.builder()
                .bucket(this.arn)
                .key(objectName)
                .build();
        PutObjectPresignRequest presignRequest = PutObjectPresignRequest.builder()
                .signatureDuration(duration)
                .putObjectRequest(objectRequest)
                .build();
        PresignedPutObjectRequest presignedPutObjectRequest = this.s3Presigner.presignPutObject(presignRequest);
        return presignedPutObjectRequest.url().toString();
    }
}
`

**Comment by LIANGQI0811** [comment]
The crt code writting by cpp for support multi-platform shared code.

I don't think it's a good strategy.

I successfully solved this problem temporarily by compiling the crt code locally a few months ago.



The following are the specific steps:

1. clone the repostrory by : https://github.com/awslabs/aws-crt-java(P.S. the aws-crt-cpp already included by git-submodule)
2. Find a machine that is exactly the same as the production environment (jdk, operating system, and cpu must be exactly the same)
3. using the `mvn compile` command compile code
4. Find the compiled dynamic link file and put it in the library file path of the production environment
5. Run a test case to verify that the problem is resolved


If you encounter any problems, you are welcome to email me

**Comment by sarahub** [comment]
I am trying to use the AwsCrtV4aSigner in the auth-cert package.  I am getting this exception that seems related to the above defect.  I saw a similar CLOSED issue in the kotlin channel.  When will CRT be supported for ALPINE?
nested exception is java.lang.UnsatisfiedLinkError: /tmp/AWSCRT_908828833976482814libaws-crt-jni.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/AWSCRT_908828833976482814libaws-crt-jni.so)] with root cause
java.lang.UnsatisfiedLinkError: /tmp/AWSCRT_908828833976482814libaws-crt-jni.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/AWSCRT_908828833976482814libaws-crt-jni.so)

**Comment by jmklix** [comment]
> When will CRT be supported for ALPINE?

This is something that we have planned, but I don't have a specific timeline for when it might get added.

**Comment by jmklix** [comment]
Alpine support was added with this release [v0.23.0](https://github.com/awslabs/aws-crt-java/releases/tag/v0.23.0). Please let us know if you have any more problems on Alpine Linux while using aws-crt-java
