### ISSUE TITLE
mvn compile fails

### ISSUE THREAD

**Issue by monelgordillo** [awslabs/aws-crt-java#563]
I'm trying to use aws-crt-java sdk.

I'm stuck at the mvn compile part. 

Plugin org.apache.maven.plugins:maven-jar-plugin:3.1.0 or one of its dependencies could not be resolved.
![20221207_170459](https://user-images.githubusercontent.com/36521543/206317612-b60691ac-832f-4468-b393-69d68f52caaa.jpg)

![20221207_170440](https://user-images.githubusercontent.com/36521543/206317754-c9333677-c1fe-47e5-81f2-fc171a33208f.jpg)

**Comment by graebm** [comment]
This error stands out to me:
> Unknown host repo.maven.apache.org: Name or service not known

the first [google](https://www.google.com/search?client=firefox-b-1-d&q=Unknown+host+repo.maven.apache.org%3A+Name+or+service+not+known) hit I get when searching that error is this [stackoverflow](https://stackoverflow.com/questions/19323678/error-in-resolving-buildtime-dependencies-while-installing-cloudstack-on-ubuntu) question. The top answer says
> This is a networking issue

**Comment by monelgordillo** [comment]
> Are you currently hacking the in-flight entertainment unit?

lol. I'm not. Its for work. 

Its Android 7 :(
