### ISSUE TITLE
S3CrtAsyncClientBuilder with path-style access

### ISSUE THREAD

**Issue by bcoromina** [awslabs/aws-crt-java#587]
Hi,

In order to build an asyn S3 client that I can benefit from multipart downloads, I use S3CrtAsyncClientBuilder instead of S3AsyncClientBuilder, but then I loose the capability of using path-style access to S3 instead of virtual-hosted style.

It would be possible to do something semantically equivalent to 
`
S3AsyncClient.crtBuilder().forcePathStyle(true).build()
`

in the same way you would do it with S3AsyncClientBuilder:

`
S3AsyncClient.builder().forcePathStyle(true).build()
`

Thanks,

Bernat

**Comment by DmitriyMusatkin** [comment]
Path Style support will need to be implemented on Java SDK side. They have an issue tracking support for it - https://github.com/aws/aws-sdk-java-v2/issues/3675
