### ISSUE TITLE
Better naming for CRT-originated threads

### ISSUE THREAD

**Issue by barryoneill** [awslabs/aws-crt-java#608]
### Describe the feature

All threads created by the CRT should be identifiable as such.

### Use Case

Right now I'm profiling a pretty sophisticated application that uses multiple libraries, each maintaining their own IO-related threadpools.   It would be a huge time saver if the CRT library didn't create anonymous sounding thread names such as `Thread-10`

![Screenshot 2023-04-21 at 2 39 33 PM](https://user-images.githubusercontent.com/885049/233711202-ca2b8a77-9410-42fd-91bd-107729d6579c.png)

### Proposed Solution

A naming scheme for created threads would be highly desireable, indicating whether that thread is I/O or CPU bound, e.g.

`crt-nonblocking-1`

or 

`crt-compute-1`

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by graebm** [comment]
Coincidentally, the very latest release https://github.com/awslabs/aws-crt-java/releases/tag/v0.21.12 from last week should be setting thread names.

The names are like "AwsEventLoop 1" (for I/O) and "AwsHostResolver"

**Comment by barryoneill** [comment]
Oh, this is great, thank you @graebm!
