### ISSUE TITLE
add getTopicAliasMaximum() to software.amazon.awssdk.crt.mqtt5.packets.ConnAckPacket

### ISSUE THREAD

**Issue by bgklika** [awslabs/aws-crt-java#618]
### Describe the feature

At the moment class [ConnAckPacket](https://awslabs.github.io/aws-crt-java/software/amazon/awssdk/crt/mqtt5/packets/ConnAckPacket.html) do not provide ability to read CONNACK  [topic alias maximum](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901088) property (id 34 0x22). 
I have tested another MQTT client on IoT Core and that property actually sent with value 8.

Please provide such method as well as parsing of 0x22 property from raw CONNACK data if missing.

### Use Case

Any CRT or SDK-based MQTT client which topic alias feature.

### Proposed Solution

Just add method and new Id in parser.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by bretambrose** [comment]
Topic aliasing is supported in the native client (https://github.com/awslabs/aws-c-mqtt/blob/v0.8.11/include/aws/mqtt/v5/mqtt5_client.h#L61-L166) but we didn't bind it out on initial MQTT5 release.  I can see about squeezing in some binding work sometime in the near future.

**Comment by bgklika** [comment]
Hello Bret!

Please take on account for planning:
1. It is not a urgent request
2. request is only for topic alias maximum not for whole topic alias feature
