### ISSUE TITLE
What are the SDK and NDK used for prebuild library so in Android aar

### ISSUE THREAD

**Issue by l0vart** [awslabs/aws-crt-java#632]
### Describe the bug

Currently we are adding this CRT with AWS iot device sdk jar into our system, which is Android 12. Want to know the SDK version and NDK version used for the prebuild library so in the aar file.

### Expected Behavior

N/A

### Current Behavior

N/A

### Reproduction Steps

N/A

### aws-crt-java version used

0.21.10

### Java version used

8

### Operating System and version

Android 12

**Comment by bretambrose** [comment]
https://github.com/awslabs/aws-crt-java/blob/v0.21.19/android/crt/build.gradle#L52-L63 possibly relevant

**Comment by l0vart** [comment]
Thanks for the info.
