### ISSUE TITLE
withTimeoutMs will throw a null pointer exception if there is no SocketOptions previously set

### ISSUE THREAD

**Issue by MikeDombo** [awslabs/aws-crt-java#650]
### Describe the bug

https://github.com/awslabs/aws-crt-java/blob/22a2275953511c492747c77c185f08f5e933caee/src/main/java/software/amazon/awssdk/crt/io/TlsConnectionOptions.java#L78

### Expected Behavior

withTimeoutMs (and similar APIs) should check for null and create default socket options if required.

### Current Behavior

Throws a NPE

### Reproduction Steps

N/A

### aws-crt-java version used

N/A

### Java version used

N/A

### Operating System and version

N/A

**Comment by jmklix** [comment]
Did you have a minimal code sample that reproduces this?

**Comment by MikeDombo** [comment]
```
try (AwsIotMqttConnectionBuilder connectionBuilder = AwsIotMqttConnectionBuilder.newMtlsBuilder(
                        thing.getCertificate().getCertificatePem(), thing.getCertificate().getKeyPair().privateKey())
                .withClientId(thing.getThingName())
                .withPort(port)
                .withTimeoutMs(30_000)
                .withEndpoint(hostAddress)
                .withBootstrap(clientBootstrap)
```

**Comment by TingDaoK** [comment]
you mean this function https://github.com/aws/aws-iot-device-sdk-java-v2/blob/main/sdk/src/main/java/software/amazon/awssdk/iot/AwsIotMqttConnectionBuilder.java#L362 instead, right?

It will be nice to have a default socket options if withTimeoutMs called before withSocketOptions, but what if user invoked `withTimeoutMs` and then `withSocketOptions` called afterward. It seems not like a good api to me.

From my point of view, it should be either:
- Remove `withTimeoutMs`, you need to specific set the socket options to set TCP socket timeout
- Or `withSocketOptionsTImeoutMs`, so it just gives you the default socket options with timeout.

**Comment by MikeDombo** [comment]
It is a very simple fix:
```
if (this.config.getSocketOptions() == null) {
   this.withSocketOptions(new SocketOptions());
}
this.config.getSocketOptions().connectTimeoutMs = timeoutMs;
```

**Comment by TingDaoK** [comment]
it's an even simpler fix for user
```
try (AwsIotMqttConnectionBuilder connectionBuilder = AwsIotMqttConnectionBuilder.newMtlsBuilder(
                        thing.getCertificate().getCertificatePem(), thing.getCertificate().getKeyPair().privateKey())
                .withClientId(thing.getThingName())
                .withPort(port)
                .withSocketOptions(new SocketOptions())
                .withTimeoutMs(30_000)
                .withEndpoint(hostAddress)
                .withBootstrap(clientBootstrap)

```
