### ISSUE TITLE
S3AsyncClient.crtBuilder() trust all certificates mode not picked up

### ISSUE THREAD

**Issue by kjc14f** [awslabs/aws-crt-java#686]
### Describe the bug

When creating an S3AsyncClient using `S3AsyncClient.crtBuilder()`, it appears the option to trust all certifiactes does not work.

I am connecting to the endpoint of an S3 compatible instance which uses a particular cert. I am not able to add this to my OS truststore of my machine so wanted to allow the client to trust any cert for my local development.

When I try to use this client with any call e.g. listing buckets, it returns an unexpected TLS error:
"Failed to send the request: TLS (SSL) negotiation failed".

When using other, non CRT clients, it fails/succeeds okay as I toggle this flag as expected.

### Expected Behavior

When setting `.trustAllCertificatesEnabled(true)` on the CRT client it should not get any TLS error as it shouldn't be checking the certs on the call against the OS truststore.

### Current Behavior

Unlike other clients, settings `.trustAllCertificatesEnabled(true)` still seems to give a TLS error when making a call

### Reproduction Steps

Create a CRT client like such:
```java
S3AsyncClient client = S3AsyncClient.crtBuilder()
  .endpointOverride("<s3 compatible url>")
  .forcePathStyle(true)
  .httpConfiguration(e -> e.trustAllCertificatesEnabled(true))
  .credentailsProvider(StaticCredentialsProvider.create(<creds>))
  .build();
```

Point the endpoint override at an instance that has a cert that is NOT in the OS truststore so you would expect to see a TLS error.
Make a call to any API e.g. `client.listBuckets().join();`.

You should see a TLS error regardless of what the value of trustAllCertificatesEnabled is.

### aws-crt-java version used

0.27.1

### Java version used

17.0.8

### Operating System and version

Windows 10 1909

**Comment by graebm** [comment]
I can reproduce this.
Investigating...

**Comment by graebm** [comment]
Fixed in the SDK's `master` branch. It should be in the next tagged release `2.20.154`
