### ISSUE TITLE
MqttClientConnection port datatype

### ISSUE THREAD

**Issue by jcosentino11** [awslabs/aws-crt-java#715]
### Describe the bug

For MQTT3 connections, it looks like signed short is being used rather than unsigned (`jchar`)
* https://github.com/awslabs/aws-crt-java/blob/00c4c16c4dfbc648c8a51549e37a863fad91aa6f/src/native/mqtt_connection.c#L577

### Expected Behavior

To be able to connect with `MqttClientConnection` using ports > 32767

### Current Behavior

```
software.amazon.awssdk.crt.mqtt.MqttException: Port must be betweeen 0 and 32767
	at software.amazon.awssdk.crt.mqtt.MqttClientConnection.connect(MqttClientConnection.java:315)
```

### Reproduction Steps

```
MqttConnectionConfig conf = new MqttConnectionConfig();
conf.setPort(40000);
...
MqttClientConnection conn = new MqttClientConnection(conf);
conn.connect();
```

### aws-crt-java version used

0.21.14

### Java version used

8

### Operating System and version

N/A

**Comment by jmklix** [comment]
This should be fixed with the latest release. Please let us know if you have any other problems with this sdk.
