### ISSUE TITLE
Seg fault in aws_java_http_stream_on_stream_destroy_fn

### ISSUE THREAD

**Issue by mark-cameraforensics** [awslabs/aws-crt-java#763]
### Describe the bug

We are seeing this error when using AWS CRT as an http client for s3. Its running in an amazon corretto container in ECS. Unfortunately I do not have the error report file as ECS killed the container:

```
# If you would like to submit a bug report, please visit:
# https://github.com/corretto/corretto-21/issues/
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
#
# A fatal error has been detected by the Java Runtime Environment:
#
# SIGSEGV (0xb) at pc=0x00007fcbc6091a25, pid=1, tid=81
#
# JRE version: OpenJDK Runtime Environment Corretto-21.0.2.13.1 (21.0.2+13) (build 21.0.2+13-LTS)
# Java VM: OpenJDK 64-Bit Server VM Corretto-21.0.2.13.1 (21.0.2+13-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C [AWSCRT_4360382152792591404libaws-crt-jni.so+0x8ba25] aws_java_http_stream_on_stream_destroy_fn+0x25
#
# Core dump will be written. Default location: /application/core.1
#
# An error report file with more information is saved as:
# /application/hs_err_pid1.log
```

### Expected Behavior

It should not seg fault.

### Current Behavior

The java process crashes

### Reproduction Steps

Unable to reproduce atm

### aws-crt-java version used

2.24.2

### Java version used

21.0.2.13.1

### Operating System and version

alpine-3.18.6

**Comment by TingDaoK** [comment]
Can you provide the CRT logs or some reproduce steps?
To enable logs from CRT, please refer to https://github.com/awslabs/aws-crt-java#system-properties

Are you using aws-crt Http client directly? Or consume it from aws-sdk-java-v2?

**Comment by jmklix** [comment]
Can you try reproducing this locally? and give us a minimal code snippet that reproduces this? We can't figure out want is wrong based on only the information above.
