### ISSUE TITLE
S3 client creation leaks memory

### ISSUE THREAD

**Issue by steven-aerts** [awslabs/aws-crt-java#823]
### Describe the bug

Every time a crt S3 client is created it will leak memory, as it is not cleaning up its TLS Contexts correctly.

This issue was detected in our production environment and is also tracked under AWS Support ticket172363023300722.

### Expected Behavior

Memory leaks

### Current Behavior

No Memory Leaks

### Reproduction Steps

Execution the following code will exhaust the memory of the machine it runs on:

```java
for(;;) {
    try(
            var tlsc = new TlsContext();
            var c = new S3Client(new S3ClientOptions()
                    .withRegion("eu-west-1")
                    .withClientBootstrap(ClientBootstrap.getOrCreateStaticDefault())
                    .withTlsContext(tlsc)
    )) {
        
    }
}
```

This snippet was derived from production usage of the higher level `S3AsyncClient.createCrt()` function.

### aws-crt-java version used

0.30.3

### Java version used

21

### Operating System and version

Linux

**Comment by jmklix** [comment]
Thanks for making the PR, we're testing it before merging it.

**Comment by jmklix** [comment]
The fix was merged [here](https://github.com/awslabs/aws-crt-java/pull/824), along with test for memory leaks
